# -*- coding: utf-8 -*-
"""GRADIO RAG Capstone .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfLbJaWjg4U63U9_9_czeSD9yk1OjlGS

# Installing Packages on Colab
"""

! pip install gradio
!pip install -q langchain langchain-openai faiss-cpu pypdf
!pip install langchain langchain-community
!pip install langchain langchain-huggingface
! pip install bs4
! pip install langchain
! pip install langchain-core
! pip install openai

"""#Importing Packages on Colab"""

import gradio as gr
import getpass
import os
import bs4
from langchain_community.document_loaders import TextLoader
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from openai import OpenAI
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from typing_extensions import List, TypedDict
from langchain_openai import OpenAIEmbeddings
from langchain_openai import ChatOpenAI
from langchain_core.vectorstores import InMemoryVectorStore
from langchain_core.prompts import ChatPromptTemplate

"""# Importing Dataset from Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

dataset = '/content/drive/MyDrive/Colab Notebooks/train_medical.txt'
with open(dataset, 'r') as f:
        text_content = f.read()

test_chatbot = text_content[:1500] #was 8260

print(test_chatbot)

test = TextLoader("train_medical.txt")
medical_chatbot = test.load()

# 2. Setting up Embeddings
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

print("Setup complete. Your chatbot is ready for testing, Let's Go Isaac!")

"""#Using OpenAI gpt-5 model"""

client = OpenAI(
  api_key=""
)
response = client.responses.create(
  model="gpt-5-nano",
  input="I forgive you",
  store=True,
)

print(response.output_text);

if not os.environ.get("OPENAI_API_KEY"):
  os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter API key for OpenAI: ")

"""# Vector Embedding to convert string to binary

*   Temperature improves novel response
*   Max tokens
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.8, max_tokens=250)
# 
# embeddings = OpenAIEmbeddings(model="text-embedding-3-large")
# vector_store = InMemoryVectorStore(embeddings)

"""#Chunking"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# text_splitter = RecursiveCharacterTextSplitter(chunk_size=250, chunk_overlap=10)
# all_splits = text_splitter.split_documents(medical_chatbot)

"""#FAISS from Chunks

*   Similarity searching
*   Clustering of vectors
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Create FAISS index from chunks
# medical_db = FAISS.from_documents(all_splits, embeddings)

"""# Prompting Instructions"""

chatbot_prompt = ChatPromptTemplate.from_messages([
    ("system", """You are an expert clinicial research assistant at Meharry Medical College, School of Medicine. You need to answer questions related to some clinical results in a  polite manner to a prospective patients.

         Follow these rules:
1. Always answer based on the provided context only. Do NOT make up an answer.
2. If unsure, say "I don't have enough information to answer that"
3. Dealing with strict confidential information divulge only information asked
4. Use bullet points if needed

Context:
{context}"""),
    ("human", "Question: {question}"),
    ("ai", "Answer: "),
])

def ask_question(question: str) -> str:
    # Retrieve context, explicitly setting k to limit documents
    retrieved_docs = medical_db.similarity_search(question, k=4)

    # Format documents
    docs_content = "\n\n".join(doc.page_content for doc in retrieved_docs)

    '''# Print the retrieved context for debugging
    print("--- Retrieved Context ---")
    print(docs_content)
    print("-------------------------")'''

    # Create prompt using your custom template
    messages = chatbot_prompt.format_messages(
        question=question,
        context=docs_content
    )

    # Get LLM response
    response = llm.invoke(messages)

    return response.content

"""# Testing Chatbot with 3 diffrent Questions and Analyzing Result"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# answer = ask_question("What were the ages of the patient in the Catheterization laboratory events and hospital outcome with direct angioplasty for acute myocardial infarction and the results?")
# print(answer)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# answer = ask_question("What was the reason for conducting the Catheterization laboratory events?")
# print(answer)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# answer = ask_question("What was the culprit of infection in renal abscees in children for both male and female. How many cases weree analyzed?")
# print(answer)

"""# GRADIO

*   Testing chatbot with user interface
*   Expires in a week so don't expect it to show past a week so no need to style for now
"""

chatbot_prompt = ChatPromptTemplate.from_messages([
    ("system", """You are an expert clinicial research assistant at Meharry Medical College, School of Medicine. You need to answer questions related to some clinical results in a  polite manner to a prospective patients.

         Follow these rules:
1. Always answer based on the provided context only. Do NOT make up an answer.
2. If unsure, say "I don't have enough information to answer that"
3. Dealing with strict confidential information divulge only information asked
4. Use bullet points if needed

Context:
{context}"""),
    ("human", "Question: {question}"),
    ("ai", "Answer: "),
])

def ask_question(question: str, history: list[list[str]]) -> str:
    # Retrieve context, explicitly setting k to limit documents
    retrieved_docs = medical_db.similarity_search(question, k=4)

    # Format documents
    docs_content = "\n\n".join(doc.page_content for doc in retrieved_docs)

    '''# Print the retrieved context for debugging
    print("--- Retrieved Context ---")
    print(docs_content)
    print("-------------------------")'''

    # Create prompt using your custom template
    messages = chatbot_prompt.format_messages(
        question=question,
        context=docs_content
    )

    # Get LLM response
    response = llm.invoke(messages)

    return response.content

# 2. Wrap it in Gradio's ChatInterface
demo = gr.ChatInterface(
    fn=ask_question,
    title="Clinical Result Chatbot Summary Cases",
    description="Testing with user interface."
)

# 3. Launch it locally (or share it)
if __name__ == "__main__":
    # Use share=True to get a public URL for 72 hours
    demo.launch(share=True)