# -*- coding: utf-8 -*-
"""Isaac's PART MSDS 560.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Bq8iQ3ywEm_Mb3TAhC6Go8E9_yDluZ3
"""

import re # Regular expressions
import nltk # Tokenisation
from nltk.util import ngrams
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from transformers import pipeline

from google.colab import drive
drive.mount('/content/drive')

dataset = '/content/drive/MyDrive/Colab Notebooks/test_medical.txt'
with open(dataset, 'r') as f:
        text_content = f.read()

text_sample = text_content[:8260]

# text sample for the first 6 cases
print(text_sample)

"""#PRE-PROCESSING: RegEx and Tokenization"""

# Text Cleaning using RegEx

text_no_space = re.sub(r"\s+", " ", text_content)
cleaned_text = text_no_space.lower()

# Clean text sample

text_no_space = re.sub(r"\s+", " ", text_content)
clean_text_sample = text_sample.lower()
#print(cleaned_text)
#print(clean_text_sample)

# Tokenization
nltk.download('punkt', quiet=True)

nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize

word_tokens = word_tokenize(cleaned_text)

#print("Tokens:", word_tokens)


# Tokenization sample_text

word_tokens_sample = word_tokenize(clean_text_sample)

print("Tokens:", word_tokens_sample)

"""# Feature Engineering: N-Gram"""

from nltk import ngrams

# Tokenize the sentence into words for both the full dataset and the sample text

tokens = nltk.word_tokenize(cleaned_text)
first_five_bigrams  = tokens[:6]
first_five_trigrams = tokens[:7]


# Generate bigrams
bigrams = list(ngrams(first_five_bigrams, 2))

# Generate trigrams
trigrams = list(ngrams(first_five_trigrams, 3))

#print("Bigrams List (first 5):", bigrams)
#print("Trigrams List (first 5):", trigrams)



# Tokenize the sentence into words for the sample text

tokens = nltk.word_tokenize(clean_text_sample)
first_twenty_bigrams  = tokens[:20]
first_twenty_trigrams = tokens[:21]


# Generate bigrams
bigrams = list(ngrams(first_twenty_bigrams, 2))

# Generate trigrams
trigrams = list(ngrams(first_twenty_trigrams, 3))

print("Bigrams List (first 20):", bigrams)
print("Trigrams List (first 20):", trigrams)

"""#Feature Engineering: Vector Semantics (Vectorization, convert string to ML for NLP)"""

! pip install gensim

import gensim
from gensim.models import Word2Vec

model=Word2Vec(sentences=cleaned_text, vector_size=150, window=7, epochs=20)
model=Word2Vec(sentences=clean_text_sample, vector_size=150, window=7, epochs=20)

"""# Chunking Text"""

# We chunked the text to make it less computationally expensive and the model cannot generate more than 1024 tokens. Each chunk of 450 words is then summarized

"""# MODELS"""

def chunk_by_words(clean_text_sample, max_words=450):
    words = clean_text_sample.split()
    chunks = []
    for i in range(0, len(words), max_words):
        chunk = " ".join(words[i:i + max_words])
        chunks.append(chunk)
    return chunks

chunks = chunk_by_words(clean_text_sample, max_words=450)
print(f"Number of chunks: {len(chunks)}")

for i, c in enumerate(chunks, 1):
    print(f"\n--- CHUNK {i} (words: {len(c.split())}) ---")
    print(c[:400], "...")

# Using Hugging Face Transfomer

# 1 SciFive

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "razent/SciFive-base-PubMed"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

def summarize_chunk_scifive_causal(chunk, max_len=1024, min_len=40):
    prompt = (
        chunk
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512
    ).to(device)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_length=max_len,       # output summary length
            min_length=min_len,
            do_sample=False,
            num_beams=4,                # small beam search
            early_stopping=True,
            no_repeat_ngram_size=3,     # key line
            repetition_penalty=1.2,     # lightly penalize repeats
            eos_token_id=tokenizer.eos_token_id,
        )

    full = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    # try to strip the prompt if it appears
    if "Summary:" in full:
        full = full.split("Summary:")[-1].strip()
    return full

partial_summaries = []
for i, chunk in enumerate(chunks, 1):
    print(f"\n=== Summarizing chunk using SciFive {i}/{len(chunks)} ===")
    s = summarize_chunk_scifive_causal(chunk, max_len=140, min_len=40)
    partial_summaries.append(s)
    print(s)

combined = " ".join(partial_summaries)

final_summary_scifive = summarize_chunk_scifive_causal(combined, max_len=1024, min_len=60)

print("\n" + "="*60)
print("FINAL SciFive SUMMARY")
print("="*60)
print(final_summary_scifive)

# 2 Pegasus

from transformers import AutoTokenizer, AutoModel, pipeline, PegasusTokenizer, PegasusForConditionalGeneration
import torch

# The Bio_ClinicalBERT model is an encoder-only model and not suitable for
# abstractive summarization with the transformers pipeline.
# To perform summarization, a sequence-to-sequence model is required.
# Let's use a Pegasus model for summarization as it's designed for this task.

# You can choose a specific Pegasus model, e.g., 'google/pegasus-cnn_dailymail'
summarization_model_name = "google/pegasus-cnn_dailymail"

summarizer_tokenizer = PegasusTokenizer.from_pretrained(summarization_model_name)
summarizer_model = PegasusForConditionalGeneration.from_pretrained(summarization_model_name)

device = "cuda" if torch.cuda.is_available() else "cpu"
summarizer_model.to(device)

# 3. Helper: summarize a single piece of text
def summarize_text(clean_text_sample, max_len=1024, min_len=40):
    inputs = summarizer_tokenizer(
        clean_text_sample,
        return_tensors="pt",
        truncation=True,
        max_length=1024,   # input limit
    ).to(device)

    with torch.no_grad():
        summary_ids = summarizer_model.generate(
            inputs["input_ids"],
            max_length=max_len,       # output summary length
            min_length=min_len,
            no_repeat_ngram_size=3,
            num_beams=4,                # small beam search
            early_stopping=True,
            repetition_penalty=1.2,
        )

    return summarizer_tokenizer.decode(summary_ids[0], skip_special_tokens=True)


# 4. Summarize each chunk, then summarize the summaries
partial_summaries = []
for i, chunk in enumerate(chunks, 1):
    print(f"\n=== Summarizing chunk using PEGASUS {i}/{len(chunks)} ===")
    s = summarize_text(chunk, max_len=140, min_len=40)
    partial_summaries.append(s)
    print(s)

combined = " ".join(partial_summaries)
final_summary_pegasus = summarize_text(combined, max_len=1024, min_len=60)

print("\n" + "="*50)
print("FINAL SUMMARY")
print("="*50)
print(final_summary_pegasus)

# 3 BioGPT

from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "microsoft/BioGPT"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

prompt = clean_text_sample + "\n\nSummary:"

inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)

with torch.no_grad():
    summary_ids = model.generate(
        **inputs,
        max_new_tokens=160,   # how long the *generated summary* can be
        do_sample=False,
        num_beams=4,                # small beam search
        early_stopping=True,
        no_repeat_ngram_size=3,     # key line
        repetition_penalty=1.2,
        eos_token_id=tokenizer.eos_token_id,
    )

summary_text = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

def summarize_chunk_with_biogpt(chunk, max_new_tokens=120):
    prompt = ( chunk
        + "\n\nSummary:"
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512
    ).to(device)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            num_beams=4,
            eos_token_id=tokenizer.eos_token_id,
        )

    full_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    # strip the prompt part if it appears in the output
    if "Summary:" in full_text:
        full_text = full_text.split("Summary:")[-1].strip()
    return full_text

partial_summaries = []
for i, chunk in enumerate(chunks, 1):
    print(f"\n=== Summarizing chunk using BioGPT{i}/{len(chunks)} ===")
    s = summarize_chunk_with_biogpt(chunk, max_new_tokens=120)
    partial_summaries.append(s)
    print(s)

# Combine and summarize again for a final “Med-PaLM style” summary
combined_text = " ".join(partial_summaries)
final_summary_biogpt = summarize_chunk_with_biogpt(combined_text, max_new_tokens=160)

print("\n" + "=" * 50)
print("FINAL SUMMARY")
print("=" * 50)
print(final_summary_biogpt)

#! pip install sacremoses

import torch
from sentence_transformers import SentenceTransformer, util
from nltk.tokenize import sent_tokenize

model = SentenceTransformer("emilyalsentzer/Bio_ClinicalBERT")

def extractive_clinicalbert_summary(clinical_text_sample, num_sentences=3):
    # 1) Split into sentences
    sentences = sent_tokenize(clinical_text_sample)

    # If no sentences, return empty string
    if len(sentences) == 0:
        return ""

    # If text has fewer sentences than requested, just return all of them
    num_sentences = min(num_sentences, len(sentences))

    # turn each sentence into a numerical vector (= embedding).
    embeddings = model.encode(sentences, convert_to_tensor=True)

    # Document embedding (mean of sentence embeddings) -> shape: (1, D)
    doc_embedding = embeddings.mean(dim=0, keepdim=True)

    # Cosine similarity each sentence vs document to rank the document (predict next word)
    scores = util.cos_sim(embeddings, doc_embedding)

    scores = scores.squeeze(1)

    top_k = torch.topk(scores, k=num_sentences)
    top_indices = top_k.indices.cpu().numpy()

    summary_sentences = [sentences[i] for i in sorted(top_indices)]

    return " ".join(summary_sentences)

extractive_summary = extractive_clinicalbert_summary(clean_text_sample, num_sentences=4)
print('ClinicalBERT summary: ', extractive_summary)

!pip install sentence-transformers

!pip install gensim

! pip install sacremoses

"""# EVALUATION METRICS"""

!pip install rouge-score
!pip install sacrebleu
!pip install bert-score

reference_summary = clean_text_sample   # gold summary from dataset
biogpt_summary = final_summary_biogpt
pegasus_summary = final_summary_pegasus
scifive_summary = final_summary_scifive
clinicalbert_summary = extractive_summary

"""# ROUGE"""

from rouge_score import rouge_scorer

def eval_rouge(reference, prediction):
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
    scores = scorer.score(reference, prediction)
    return scores

print("ROUGE for BioGPT:", eval_rouge(reference_summary, biogpt_summary))
print("ROUGE for PEGASUS:", eval_rouge(reference_summary, pegasus_summary))
print("ROUGE for SciFive:", eval_rouge(reference_summary, scifive_summary))
print("ROUGE for ClinicalBERT:", eval_rouge(reference_summary, clinicalbert_summary))

"""# BLEU"""

import sacrebleu

def eval_bleu(reference, prediction):
    bleu = sacrebleu.corpus_bleu([prediction], [[reference]])
    return bleu.score

print("BLEU for BioGPT:", eval_bleu(reference_summary, biogpt_summary))
print("BLEU for PEGASUS:", eval_bleu(reference_summary, pegasus_summary))
print("BLEU for SciFive:", eval_bleu(reference_summary, scifive_summary))
print("BLEU for ClinicalBERT:", eval_bleu(reference_summary, clinicalbert_summary))

"""# BERT-SCORE"""

from bert_score import score

def bert_score_eval(reference_summary, generated_summary, lang="en"):
    """
    Computes BERTScore Precision, Recall, and F1.
    Input: reference summary (string), generated summary (string)
    Output: dict with P, R, F1
    """
    P, R, F1 = score([generated_summary], [reference_summary], lang=lang)
    return {
        "BERTScore_P": float(P[0]),
        "BERTScore_R": float(R[0]),
        "BERTScore_F1": float(F1[0])
    }


print("BERTScore for BioGPT")
print(bert_score_eval(reference_summary, biogpt_summary))

print("\n BERTScore for PEGASUS")
print(bert_score_eval(reference_summary, pegasus_summary))

print("\n BERTScore for SciFive ")
print(bert_score_eval(reference_summary, scifive_summary))

print("\n BERTScore for ClinicalBERT (extractive)")
print(bert_score_eval(reference_summary, clinicalbert_summary))

"""# ROUGE SCORE VISUAL"""

# --- Import required libraries ---
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# --- Create dataset from your ROUGE results ---
data = {
    'Model': ['BioGPT', 'PEGASUS', 'SciFive', 'ClinicalBERT'],
    'ROUGE-1_Prec': [0.9927, 0.9210, 0.8281, 1.0000],
    'ROUGE-1_Rec':  [0.3382, 0.0288, 0.0436, 0.0897],
    'ROUGE-1_F1':   [0.5046, 0.0559, 0.0829, 0.1647],
    'ROUGE-2_Prec': [0.9782, 0.8108, 0.3016, 0.9722],
    'ROUGE-2_Rec':  [0.3327, 0.0247, 0.0157, 0.0865],
    'ROUGE-2_F1':   [0.4966, 0.0480, 0.0298, 0.1589],
    'ROUGE-L_Prec': [0.9879, 0.8421, 0.4218, 1.0000],
    'ROUGE-L_Rec':  [0.3366, 0.0263, 0.0222, 0.0897],
    'ROUGE-L_F1':   [0.5021, 0.0511, 0.0422, 0.1647]
}

df = pd.DataFrame(data)
df.set_index('Model', inplace=True)

# --- Compute average F1 across metrics ---
df['Avg_F1'] = df[['ROUGE-1_F1','ROUGE-2_F1','ROUGE-L_F1']].mean(axis=1)

# --- 1️⃣ Grouped Bar Plot: ROUGE F1 Scores ---
rouge_f1 = df[['ROUGE-1_F1','ROUGE-2_F1','ROUGE-L_F1']]

rouge_f1.plot(kind='bar', figsize=(8,5))
plt.title('ROUGE F1-Score Comparison Across Models')
plt.ylabel('F1-Score')
plt.ylim(0, 0.55)
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(title='ROUGE Metric')
plt.show()

# --- 2️⃣ Average F1 Comparison Bar Chart ---
plt.figure(figsize=(6,4))
plt.bar(df.index, df['Avg_F1'], color=['#2E86AB','#F6AA1C','#A23E48','#2E8B57'])
plt.title('Average ROUGE F1 Score by Model')
plt.ylabel('Average F1')
plt.ylim(0, 0.55)
plt.grid(axis='y', linestyle='--', alpha=0.7)
for i, val in enumerate(df['Avg_F1']):
    plt.text(i, val + 0.01, f"{val:.3f}", ha='center')
plt.show()

# --- 3️⃣ (Optional) Radar Plot: Model Comparison Across ROUGE Metrics ---
import matplotlib.pyplot as plt

labels = ['ROUGE-1', 'ROUGE-2', 'ROUGE-L']
num_vars = len(labels)
angles = np.linspace(0, 2*np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]

fig, ax = plt.subplots(figsize=(6,6), subplot_kw=dict(polar=True))
for model, row in df.iterrows():
    values = row[['ROUGE-1_F1','ROUGE-2_F1','ROUGE-L_F1']].tolist()
    values += values[:1]
    ax.plot(angles, values, label=model)
    ax.fill(angles, values, alpha=0.1)

ax.set_xticks(angles[:-1])
ax.set_xticklabels(labels)
ax.set_yticks([0.1, 0.3, 0.5])
ax.set_yticklabels(['0.1','0.3','0.5'])
ax.set_ylim(0, 0.55)
plt.title('ROUGE F1 Radar Comparison Across Models')
plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
plt.show()

"""# BERT-Score Visual"""

# --- Import libraries ---
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# --- Create a DataFrame from your BERTScore results ---
bert_data = {
    'Model': ['BioGPT', 'PEGASUS', 'SciFive', 'ClinicalBERT'],
    'Precision': [0.9864, 0.8038, 0.8713, 0.8558],
    'Recall':    [0.9846, 0.7673, 0.7907, 0.8118],
    'F1':        [0.9855, 0.7851, 0.8291, 0.8332]
}

df = pd.DataFrame(bert_data)
df.set_index('Model', inplace=True)

# --- 1️⃣ Grouped Bar Chart: Precision, Recall, F1 ---
plt.figure(figsize=(8,5))
df.plot(kind='bar', color=['#1f77b4','#ff7f0e','#2ca02c'])
plt.title('BERTScore Comparison Across Models', fontsize=14, weight='bold')
plt.ylabel('Score', fontsize=12)
plt.xlabel('')
plt.ylim(0.7, 1.0)
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.legend(title='Metric', bbox_to_anchor=(1.05, 1), loc='upper left')

# Annotate bar values
for i, col in enumerate(df.columns):
    for j, val in enumerate(df[col]):
        plt.text(j + (i-1)*0.25 + 0.1, val + 0.005, f"{val:.3f}", ha='center', fontsize=9)

plt.tight_layout()
plt.show()

# --- 2️⃣ Optional: Radar Chart for Visual Balance ---
labels = ['Precision', 'Recall', 'F1']
num_vars = len(labels)

angles = np.linspace(0, 2*np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]

fig, ax = plt.subplots(figsize=(6,6), subplot_kw=dict(polar=True))
for model, row in df.iterrows():
    values = row.tolist()
    values += values[:1]
    ax.plot(angles, values, label=model)
    ax.fill(angles, values, alpha=0.1)

ax.set_xticks(angles[:-1])
ax.set_xticklabels(labels, fontsize=11)
ax.set_yticks([0.7, 0.8, 0.9, 1.0])
ax.set_yticklabels(['0.7','0.8','0.9','1.0'])
ax.set_ylim(0.7, 1.0)
plt.title('BERTScore Radar Comparison', fontsize=14, weight='bold')
plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
plt.show()

"""#BLEU SCORE VISUAL"""

# --- Import libraries ---
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# --- Create DataFrame ---
bleu_data = {
    'Model': ['BioGPT', 'PEGASUS', 'SciFive', 'ClinicalBERT'],
    'BLEU': [14.1886, 4.0977e-12, 6.3388e-06, 0.0029]
}

df_bleu = pd.DataFrame(bleu_data)
df_bleu.set_index('Model', inplace=True)

# --- 1️⃣ Simple Bar Chart (linear scale) ---
plt.figure(figsize=(7,5))
plt.bar(df_bleu.index, df_bleu['BLEU'], color=['#2E86AB','#F6AA1C','#A23E48','#2E8B57'])
plt.title('BLEU Score Comparison Across Summarization Models', fontsize=14, weight='bold')
plt.ylabel('BLEU Score')
plt.grid(axis='y', linestyle='--', alpha=0.6)
for i, v in enumerate(df_bleu['BLEU']):
    plt.text(i, v + 0.2, f"{v:.4f}", ha='center', fontsize=9)
plt.tight_layout()
plt.show()

# --- 2️⃣ Log-Scale Bar Chart (to show relative magnitude differences clearly) ---
plt.figure(figsize=(7,5))
plt.bar(df_bleu.index, df_bleu['BLEU'], color=['#2E86AB','#F6AA1C','#A23E48','#2E8B57'])
plt.yscale('log')
plt.title('BLEU Score (Log Scale) — Clinical Text Summarization', fontsize=14, weight='bold')
plt.ylabel('BLEU Score (log scale)')
plt.grid(axis='y', linestyle='--', alpha=0.6)
for i, v in enumerate(df_bleu['BLEU']):
    plt.text(i, v * 1.2, f"{v:.2e}", ha='center', fontsize=9)
plt.tight_layout()
plt.show()